// Mocks generated by Mockito 5.0.17 from annotations
// in ny_times_popular_articles/test/article_controller_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ny_times_popular_articles/models/article_model.dart' as _i4;
import 'package:ny_times_popular_articles/services/article_service.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ArticleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticleService extends _i1.Mock implements _i2.ArticleService {
  MockArticleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Article>> getPopularArticles(_i5.Client? client) =>
      (super.noSuchMethod(Invocation.method(#getPopularArticles, [client]),
              returnValue: Future<List<_i4.Article>>.value(<_i4.Article>[]))
          as _i3.Future<List<_i4.Article>>);
}
