include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - always_use_package_imports
    - prefer_single_quotes
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters
    - annotate_overrides
    - await_only_futures
    - constant_identifier_names
    - control_flow_in_finally
    - camel_case_types
    - avoid_returning_null_for_future
    - empty_statements
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
